//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Core.BusinessEntity
{
    using QN.EDF.Model;
    
    
    public class MngUserBO : TEdfMngUser
    {
        
        
        /// <summary>
        /// created by name
        /// </summary>
        public string? created_by_name { get; set; }

        /// <summary>
        /// last updated by name
        /// </summary>
        public string? last_updated_by_name { get; set; }
    }
}
