//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.BusinessEntity
{
    using QN.EDF.Model;
    
    
    public class PhotoPriceBiz : QNBizBase
    {
        
        
        /// <summary>
        /// 分类
        /// </summary>
        public string? CategoryId { get; set; }
        
        /// <summary>
        /// 价格
        /// </summary>
        public string? PriceInfo { get; set; }
        
        /// <summary>
        /// 备注
        /// </summary>
        public string? SubTitle { get; set; }
    }
}
