//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.BusinessEntity
{
    using QN.EDF.Model;


    public class PhotoCategoryBiz : QNBizBase
    {


        /// <summary>
        /// 名称
        /// </summary>
        public string? Name { get; set; }

        public string? Price { get; set; }

        public string SubTitle { get; set; }

        /// <summary>
        /// 缩略图
        /// </summary>
        public string? Thumb { get; set; }

        /// <summary>
        /// 父级
        /// </summary>
        public string? ParentId { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        public string? Remark { get; set; }

        public string? ParentName { get; set; }

        public List<PhotoImgBiz> Images { get; set; }

        public string ImgStr { get; set; }

        public List<PhotoCategoryBiz> Sub { get; set; }
    }
}
