//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.DataAccess
{
    using QN.EDF.Data;
    using QN.EDF.Common;
    using QN.EDF.Model;
    using Dapper;
    using System.Data;
    using QN.Ots.Photo.Photo.BusinessEntity;
    using MySql.Data.MySqlClient;

    public class PhotoCategoryDataAccess : QNDataAccessBase
    {

        public (List<PhotoCategoryBO>, int) GetPhotoCategoryPaging(PageRequest<PhotoCategoryBO> data)
        {
            //using (Helper.C1)
            {
                var dic = data.Transfer(QNCommonConstants.OptType.Page);
                List<PhotoCategoryBO> result = Helper.C1.Query<PhotoCategoryBO>("P_PHOTO_CATEGORY_P", dic, commandType: CommandType.StoredProcedure).ToList();
                Int32 totalNum = result.Count > 0 ? dic.Get<Int32>(QNCommonConstants.DataOperation.StoredProcedureParam.TotalNum.ToLower()) : 0;

                return (result, totalNum);
            }
        }

        public List<PhotoCategoryBO> GetPhotoCategory(QueryRequest<PhotoCategoryBO> data)
        {
            //using (Helper.C1)
            {
                var dic = data.Transfer();
                List<PhotoCategoryBO> result = Helper.C1.Query<PhotoCategoryBO>("P_PHOTO_CATEGORY_S", dic, commandType: CommandType.StoredProcedure).ToList();

                return result;
            }
        }

        public int AddPhotoCategory(List<TPhotoCategory> data)
        {
            //using (Helper.C1)
            {
                var affected = 0;

                data.ForEach(p =>
                {
                    var dic = p.Transfer();
                    affected += Helper.C1.Execute("P_PHOTO_CATEGORY_I", dic, commandType: CommandType.StoredProcedure);
                });

                return affected;
            }
        }

        public int UpdatePhotoCategory(List<TPhotoCategory> data)
        {
            //using (Helper.C1)
            {
                var affected = 0;

                data.ForEach(p =>
                {
                    var dic = p.Transfer();
                    affected += Helper.C1.Execute("P_PHOTO_CATEGORY_U", dic, commandType: CommandType.StoredProcedure);
                });

                return affected;
            }
        }

        public int DeletePhotoCategory(QNIDParam data)
        {
            //using (Helper.C1)
            {
                var affected = 0;

                data.ids.ForEach(id =>
                {
                    var dic = id.Transfer();
                    dic["p_is_physical"] = 1;
                    affected += Helper.C1.Execute("P_PHOTO_CATEGORY_D", dic, commandType: CommandType.StoredProcedure);
                });

                return affected;
            }
        }
    }
}
