//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Core.BusinessComponent
{
    using QN.EDF.Common;
    using QN.EDF.Model;
    using QN.Ots.Photo.Core.DataAccess;
    using QN.Ots.Photo.Core.BusinessEntity;
    
    
    public class ApiUserBusinessComponent
    {
        
        private ApiUserDataAccess da = QNInjection.Build<ApiUserDataAccess>();
        
        public (List<ApiUserBO>, int) GetApiUserPaging(PageRequest<ApiUserBO> data)
        {
            var result = da.GetApiUserPaging(data);
            return result;
        }
        
        public List<ApiUserBO> GetApiUser(QueryRequest<ApiUserBO> data)
        {
            var result = da.GetApiUser(data);
            return result;
        }
        
        public int AddApiUser(List<TEdfApiUser> data)
        {
            int result = da.AddApiUser(data);
            return result;
        }
        
        public int UpdateApiUser(List<TEdfApiUser> data)
        {
            int result = da.UpdateApiUser(data);
            return result;
        }
        
        public int DeleteApiUser(QNIDParam data)
        {
            int result = da.DeleteApiUser(data);
            return result;
        }
    }
}
