//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Core.DataAccess
{
    using QN.EDF.Data;
    using QN.EDF.Common;
    using QN.EDF.Model;
    using Dapper;
    using System.Data;
    using QN.Ots.Photo.Core.BusinessEntity;
    using MySql.Data.MySqlClient;
    using System.Data.Common;

    public class MngUserDataAccess : QNDataAccessBase
    {

        public (List<MngUserBO>, int) GetMngUserPaging(PageRequest<MngUserBO> data)
        {

            var dic = data.Transfer(QNCommonConstants.OptType.Page);
            List<MngUserBO> result = Helper.C1.Query<MngUserBO>("P_EDF_MNG_USER_P", dic, commandType: CommandType.StoredProcedure).ToList();
            Int32 totalNum = result.Count > 0 ? dic.Get<Int32>(QNCommonConstants.DataOperation.StoredProcedureParam.TotalNum) : 0;
            
            return (result, totalNum);
        }

        public List<MngUserBO> GetMngUser(QueryRequest<MngUserBO> data)
        {
            var dic = data.Transfer();
            List<MngUserBO> result = Helper.C1.Query<MngUserBO>("P_EDF_MNG_USER_S", dic, commandType: CommandType.StoredProcedure).ToList();
            return result;
        }

        public int AddMngUser(List<TEdfMngUser> data)
        {

            var affected = 0;

            data.ForEach(p =>
            {
                var dic = p.Transfer();
                affected += Helper.C1.Execute("P_EDF_MNG_USER_I", dic, commandType: CommandType.StoredProcedure);
            });

            
            return affected;
        }

        public int UpdateMngUser(List<TEdfMngUser> data)
        {

            var affected = 0;

            data.ForEach(p =>
            {
                var dic = p.Transfer();
                affected += Helper.C1.Execute("P_EDF_MNG_USER_U", dic, commandType: CommandType.StoredProcedure);
            });

            
            return affected;
        }

        public int DeleteMngUser(QNIDParam data)
        {

            var affected = 0;

            var dic = data.Transfer();
            affected += Helper.C1.Execute("P_EDF_MNG_USER_D", dic, commandType: CommandType.StoredProcedure);

            
            return affected;
        }
    }
}
