//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.BusinessComponent
{
    using QN.EDF.Common;
    using QN.EDF.Model;
    using QN.Ots.Photo.Photo.DataAccess;
    using QN.Ots.Photo.Photo.BusinessEntity;
    
    
    public class PhotoImgBusinessComponent
    {
        
        private PhotoImgDataAccess da = QNInjection.Build<PhotoImgDataAccess>();
        
        public (List<PhotoImgBO>, int) GetPhotoImgPaging(PageRequest<PhotoImgBO> data)
        {
            var result = da.GetPhotoImgPaging(data);
            return result;
        }
        
        public List<PhotoImgBO> GetPhotoImg(QueryRequest<PhotoImgBO> data)
        {
            var result = da.GetPhotoImg(data);
            return result;
        }
        
        public int AddPhotoImg(List<TPhotoImg> data)
        {
            int result = da.AddPhotoImg(data);
            return result;
        }
        
        public int UpdatePhotoImg(List<TPhotoImg> data)
        {
            int result = da.UpdatePhotoImg(data);
            return result;
        }
        
        public int DeletePhotoImg(QNIDParam data)
        {
            int result = da.DeletePhotoImg(data);
            return result;
        }
    }
}
