//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.BusinessComponent
{
    using QN.EDF.Common;
    using QN.EDF.Model;
    using QN.Ots.Photo.Photo.DataAccess;
    using QN.Ots.Photo.Photo.BusinessEntity;
    
    
    public class PhotoPriceBusinessComponent
    {
        
        private PhotoPriceDataAccess da = QNInjection.Build<PhotoPriceDataAccess>();
        
        public (List<PhotoPriceBO>, int) GetPhotoPricePaging(PageRequest<PhotoPriceBO> data)
        {
            var result = da.GetPhotoPricePaging(data);
            return result;
        }
        
        public List<PhotoPriceBO> GetPhotoPrice(QueryRequest<PhotoPriceBO> data)
        {
            var result = da.GetPhotoPrice(data);
            return result;
        }
        
        public int AddPhotoPrice(List<TPhotoPrice> data)
        {
            int result = da.AddPhotoPrice(data);
            return result;
        }
        
        public int UpdatePhotoPrice(List<TPhotoPrice> data)
        {
            int result = da.UpdatePhotoPrice(data);
            return result;
        }
        
        public int DeletePhotoPrice(QNIDParam data)
        {
            int result = da.DeletePhotoPrice(data);
            return result;
        }
    }
}
