//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.BusinessComponent
{
    using QN.EDF.Common;
    using QN.EDF.Model;
    using QN.Ots.Photo.Photo.DataAccess;
    using QN.Ots.Photo.Photo.BusinessEntity;
    
    
    public class PhotoBookingBusinessComponent
    {
        
        private PhotoBookingDataAccess da = QNInjection.Build<PhotoBookingDataAccess>();
        
        public (List<PhotoBookingBO>, int) GetPhotoBookingPaging(PageRequest<PhotoBookingBO> data)
        {
            var result = da.GetPhotoBookingPaging(data);
            return result;
        }
        
        public List<PhotoBookingBO> GetPhotoBooking(QueryRequest<PhotoBookingBO> data)
        {
            var result = da.GetPhotoBooking(data);
            return result;
        }
        
        public int AddPhotoBooking(List<TPhotoBooking> data)
        {
            int result = da.AddPhotoBooking(data);
            return result;
        }
        
        public int UpdatePhotoBooking(List<TPhotoBooking> data)
        {
            int result = da.UpdatePhotoBooking(data);
            return result;
        }
        
        public int DeletePhotoBooking(QNIDParam data)
        {
            int result = da.DeletePhotoBooking(data);
            return result;
        }
    }
}
