//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Core.BusinessEntity
{
    using QN.EDF.Model;
    
    
    public class MngUserBiz : QNBizBase
    {
        
        
        /// <summary>
        /// 昵称
        /// </summary>
        public string? NickName { get; set; }
        
        /// <summary>
        /// 名称
        /// </summary>
        public string? UserName { get; set; }
        
        /// <summary>
        /// 电话
        /// </summary>
        public string? Phone { get; set; }
        
        /// <summary>
        /// 密码
        /// </summary>
        public string? Pwd { get; set; }
        
        /// <summary>
        /// 明文
        /// </summary>
        public string? PwdText { get; set; }
        
        /// <summary>
        /// 账号
        /// </summary>
        public string? Account { get; set; }
        
        /// <summary>
        /// 邮箱
        /// </summary>
        public string? Email { get; set; }
        
        /// <summary>
        /// 描述
        /// </summary>
        public string? Remark { get; set; }
        
        /// <summary>
        /// 上次登陆
        /// </summary>
        public DateTime? LastLoginTime { get; set; }

        /// <summary>
        /// WX UID
        /// </summary>
        public string Uid { get; set; }

        /// <summary>
        /// WX Open ID
        /// </summary>
        public string OpenId { get; set; }

        /// <summary>
        /// OA Open ID
        /// </summary>
        public string OaOpenId { get; set; }

        /// <summary>
        /// Session Key
        /// </summary>
        public string SessionKey { get; set; }
    }
}
