//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Core.ServiceInterface
{
    using QN.EDF.Model;
    using QN.Ots.Photo.Core.BusinessEntity;
    
    
    public interface IApiUserSI
    {
        
        BizData<(List<ApiUserBiz>, int)> GetApiUserPaging(PageRequest<ApiUserBiz> data);
        
        BizData<List<ApiUserBiz>> GetApiUser(QueryRequest<ApiUserBiz> data);
        
        BizData<ApiUserBiz> GetApiUserDetail(ApiUserBiz data);
        
        BizData<int> AddApiUser(List<ApiUserBiz> data);
        
        BizData<int> UpdateApiUser(List<ApiUserBiz> data);
        
        BizData<int> DeleteApiUser(QNIDParamBiz data);
        
        BizData<int> DataStatusApiUser(QNIDParamBiz data);
        
        BizData<QNExcelExportData> ExportApiUser(PageRequest<ApiUserBiz> data);
        
        BizData<QNUserInfoBiz> LoginApiUser(QueryRequest<LoginBiz> data);
        
        BizData<QNUserInfoBiz> GetCurrentApiUser();
    }
}
