//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Core.ServiceInterface
{
    using QN.EDF.Model;
    using QN.Ots.Photo.Core.BusinessEntity;
    
    
    public interface IMngUserSI
    {
        
        BizData<(List<MngUserBiz>, int)> GetMngUserPaging(PageRequest<MngUserBiz> data);
        
        BizData<List<MngUserBiz>> GetMngUser(QueryRequest<MngUserBiz> data);
        
        BizData<MngUserBiz> GetMngUserDetail(MngUserBiz data);
        
        BizData<int> AddMngUser(List<MngUserBiz> data);
        
        BizData<int> UpdateMngUser(List<MngUserBiz> data);
        
        BizData<int> DeleteMngUser(QNIDParamBiz data);
        
        BizData<int> DataStatusMngUser(QNIDParamBiz data);
        
        BizData<QNExcelExportData> ExportMngUser(PageRequest<MngUserBiz> data);
        
        BizData<QNUserInfoBiz> LoginMngUser(QueryRequest<LoginBiz> data);
        
        BizData<QNUserInfoBiz> GetCurrentMngUser();
    }
}
