//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Core.BusinessEntity
{
    using QN.EDF.Model;
    
    
    public class TEdfMngUser : MySQLDOBase
    {
        
        
        /// <summary>
        /// 昵称
        /// </summary>
        public string? nick_name { get; set; }
        
        /// <summary>
        /// 名称
        /// </summary>
        public string? user_name { get; set; }
        
        /// <summary>
        /// 电话
        /// </summary>
        public string? phone { get; set; }
        
        /// <summary>
        /// 密码
        /// </summary>
        public string? pwd { get; set; }
        
        /// <summary>
        /// 明文
        /// </summary>
        public string? pwd_text { get; set; }
        
        /// <summary>
        /// 账号
        /// </summary>
        public string? account { get; set; }
        
        /// <summary>
        /// 邮箱
        /// </summary>
        public string? email { get; set; }
        
        /// <summary>
        /// 描述
        /// </summary>
        public string? remark { get; set; }
        
        /// <summary>
        /// 上次登陆
        /// </summary>
        public DateTime? last_login_time { get; set; }

        /// <summary>
        /// WX UID
        /// </summary>
        public string uid { get; set; }

        /// <summary>
        /// WX Open ID
        /// </summary>
        public string open_id { get; set; }

        /// <summary>
        /// OA Open ID
        /// </summary>
        public string oa_open_id { get; set; }

        /// <summary>
        /// Session Key
        /// </summary>
        public string session_key { get; set; }
    }
}
