//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.ServiceInterface
{
    using QN.EDF.Model;
    using QN.Ots.Photo.Photo.BusinessEntity;
    
    
    public interface IPhotoBookingSI
    {
        
        BizData<(List<PhotoBookingBiz>, int)> GetPhotoBookingPaging(PageRequest<PhotoBookingBiz> data);
        
        BizData<List<PhotoBookingBiz>> GetPhotoBooking(QueryRequest<PhotoBookingBiz> data);
        
        BizData<PhotoBookingBiz> GetPhotoBookingDetail(PhotoBookingBiz data);
        
        BizData<int> AddPhotoBooking(List<PhotoBookingBiz> data);
        
        BizData<int> UpdatePhotoBooking(List<PhotoBookingBiz> data);
        
        BizData<int> DeletePhotoBooking(QNIDParamBiz data);
        
        BizData<int> DataStatusPhotoBooking(QNIDParamBiz data);
        
        BizData<QNExcelExportData> ExportPhotoBooking(PageRequest<PhotoBookingBiz> data);
    }
}
