//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.ServiceInterface
{
    using QN.EDF.Model;
    using QN.Ots.Photo.Photo.BusinessEntity;
    
    
    public interface IPhotoCategorySI
    {
        
        BizData<(List<PhotoCategoryBiz>, int)> GetPhotoCategoryPaging(PageRequest<PhotoCategoryBiz> data);
        
        BizData<List<PhotoCategoryBiz>> GetPhotoCategory(QueryRequest<PhotoCategoryBiz> data);
        
        BizData<PhotoCategoryBiz> GetPhotoCategoryDetail(PhotoCategoryBiz data);
        
        BizData<int> AddPhotoCategory(List<PhotoCategoryBiz> data);
        
        BizData<int> UpdatePhotoCategory(List<PhotoCategoryBiz> data);
        
        BizData<int> DeletePhotoCategory(QNIDParamBiz data);
        
        BizData<int> DataStatusPhotoCategory(QNIDParamBiz data);
        
        BizData<QNExcelExportData> ExportPhotoCategory(PageRequest<PhotoCategoryBiz> data);
    }
}
