//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.ServiceInterface
{
    using QN.EDF.Model;
    using QN.Ots.Photo.Photo.BusinessEntity;
    
    
    public interface IPhotoPriceSI
    {
        
        BizData<(List<PhotoPriceBiz>, int)> GetPhotoPricePaging(PageRequest<PhotoPriceBiz> data);
        
        BizData<List<PhotoPriceBiz>> GetPhotoPrice(QueryRequest<PhotoPriceBiz> data);
        
        BizData<PhotoPriceBiz> GetPhotoPriceDetail(PhotoPriceBiz data);
        
        BizData<int> AddPhotoPrice(List<PhotoPriceBiz> data);
        
        BizData<int> UpdatePhotoPrice(List<PhotoPriceBiz> data);
        
        BizData<int> DeletePhotoPrice(QNIDParamBiz data);
        
        BizData<int> DataStatusPhotoPrice(QNIDParamBiz data);
        
        BizData<QNExcelExportData> ExportPhotoPrice(PageRequest<PhotoPriceBiz> data);
    }
}
