//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.Photo.ServiceInterface
{
    using QN.EDF.Model;
    using QN.Ots.Photo.Photo.BusinessEntity;
    
    
    public interface IPhotoImgSI
    {
        
        BizData<(List<PhotoImgBiz>, int)> GetPhotoImgPaging(PageRequest<PhotoImgBiz> data);
        
        BizData<List<PhotoImgBiz>> GetPhotoImg(QueryRequest<PhotoImgBiz> data);
        
        BizData<PhotoImgBiz> GetPhotoImgDetail(PhotoImgBiz data);
        
        BizData<int> AddPhotoImg(List<PhotoImgBiz> data);
        
        BizData<int> UpdatePhotoImg(List<PhotoImgBiz> data);
        
        BizData<int> DeletePhotoImg(QNIDParamBiz data);
        
        BizData<int> DataStatusPhotoImg(QNIDParamBiz data);
        
        BizData<QNExcelExportData> ExportPhotoImg(PageRequest<PhotoImgBiz> data);
    }
}
