//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.API.Hosting.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using QN.EDF.Common;
    using QN.EDF.Model;
    using QN.Ots.Photo.Core.BusinessEntity;
    using QN.Ots.Photo.Core.ServiceInterface;
    using QN.Ots.Photo.API.Hosting.Framework;
    using QN.Ots.Photo.Photo.BusinessEntity;
    using QN.Ots.Photo.Photo.ServiceInterface;
    
    
    public class PhotoBookingController : PhotoAPIBaseController
    {
        
        private static IPhotoBookingSI si = QNInjection.Build<IPhotoBookingSI>();
        
        private static IHttpContextAccessor http = QNInjection.Build<IHttpContextAccessor>();
        
        private static IWebHostEnvironment webHost = QNInjection.Build<IWebHostEnvironment>();
        
        [HttpPost()]
        [Route("photo/list-photo-booking")]
        public IActionResult GetPhotoBookingPaging([FromBody] PageRequest<PhotoBookingBiz> data)
        {

            BizData<(List<PhotoBookingBiz>, int)> bizResponse = si.GetPhotoBookingPaging(data);
            var apiData = bizResponse.Transfer<PhotoBookingBiz, List<PhotoBookingBiz>>(data.Current, data.PageSize);
            return Ok(apiData);
        }
        
        [HttpPost()]
        [Route("photo/add-photo-booking")]
        public IActionResult AddPhotoBooking([FromBody] PhotoBookingBiz data)
        {

            BizData<int> bizResponse = si.AddPhotoBooking(new List<PhotoBookingBiz>() {data});
            var apiData = bizResponse.Transfer<ApiData<int>>();
            return Ok(apiData);
        }
        
        [HttpPost()]
        [Route("photo/update-photo-booking")]
        public IActionResult UpdatePhotoBooking([FromBody] PhotoBookingBiz data)
        {

            BizData<int> bizResponse = si.UpdatePhotoBooking(new List<PhotoBookingBiz>() {data});
            var apiData = bizResponse.Transfer<ApiData<int>>();
            return Ok(apiData);
        }
        
        [HttpGet()]
        [Route("photo/detail-photo-booking")]
        public IActionResult GetPhotoBookingDetail([FromQuery] PhotoBookingBiz data)
        {

            BizData<PhotoBookingBiz> bizResponse = si.GetPhotoBookingDetail(data);
            var apiData = bizResponse.Transfer<ApiData<PhotoBookingBiz>>();
            return Ok(apiData);
        }
        
        [HttpPost()]
        [Route("photo/delete-photo-booking")]
        public IActionResult DeletePhotoBooking([FromBody] QNIDParamBiz data)
        {

            BizData<int> bizResponse = si.DeletePhotoBooking(data);
            var apiData = bizResponse.Transfer<ApiData<int>>();
            return Ok(apiData);
        }
        
        [HttpPost()]
        [Route("photo/export-photo-booking")]
        public IActionResult ExportPhotoBooking()
        {

            BizData<QNExcelExportData> biz = si.ExportPhotoBooking(new PageRequest<PhotoBookingBiz>());
            FileStreamResult fsr = File(biz.Data.ExportStream, biz.Data.OutFormat, biz.Data.FileName);
            return fsr;
        }
    }
}
