//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QN.Ots.Photo.API.Hosting.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using QN.EDF.Common;
    using QN.EDF.Model;
    using QN.Ots.Photo.Core.BusinessEntity;
    using QN.Ots.Photo.Core.ServiceInterface;
    using QN.Ots.Photo.API.Hosting.Framework;
    using QN.Ots.Photo.Photo.BusinessEntity;
    using QN.Ots.Photo.Photo.ServiceInterface;
    
    
    public class PhotoCategoryController : PhotoAPIBaseController
    {
        
        private static IPhotoCategorySI si = QNInjection.Build<IPhotoCategorySI>();
        
        private static IHttpContextAccessor http = QNInjection.Build<IHttpContextAccessor>();
        
        private static IWebHostEnvironment webHost = QNInjection.Build<IWebHostEnvironment>();
        
        [HttpPost()]
        [Route("photo/list-photo-category")]
        public IActionResult GetPhotoCategoryPaging([FromBody] PageRequest<PhotoCategoryBiz> data)
        {

            BizData<(List<PhotoCategoryBiz>, int)> bizResponse = si.GetPhotoCategoryPaging(data);
            var apiData = bizResponse.Transfer<PhotoCategoryBiz, List<PhotoCategoryBiz>>(data.Current, data.PageSize);
            return Ok(apiData);
        }
        
        [HttpPost()]
        [Route("photo/add-photo-category")]
        public IActionResult AddPhotoCategory([FromBody] PhotoCategoryBiz data)
        {

            BizData<int> bizResponse = si.AddPhotoCategory(new List<PhotoCategoryBiz>() {data});
            var apiData = bizResponse.Transfer<ApiData<int>>();
            return Ok(apiData);
        }
        
        [HttpPost()]
        [Route("photo/update-photo-category")]
        public IActionResult UpdatePhotoCategory([FromBody] PhotoCategoryBiz data)
        {

            BizData<int> bizResponse = si.UpdatePhotoCategory(new List<PhotoCategoryBiz>() {data});
            var apiData = bizResponse.Transfer<ApiData<int>>();
            return Ok(apiData);
        }
        
        [HttpGet()]
        [Route("photo/detail-photo-category")]
        public IActionResult GetPhotoCategoryDetail([FromQuery] PhotoCategoryBiz data)
        {

            BizData<PhotoCategoryBiz> bizResponse = si.GetPhotoCategoryDetail(data);
            var apiData = bizResponse.Transfer<ApiData<PhotoCategoryBiz>>();
            return Ok(apiData);
        }
        
        [HttpPost()]
        [Route("photo/delete-photo-category")]
        public IActionResult DeletePhotoCategory([FromBody] QNIDParamBiz data)
        {

            BizData<int> bizResponse = si.DeletePhotoCategory(data);
            var apiData = bizResponse.Transfer<ApiData<int>>();
            return Ok(apiData);
        }
        
        [HttpPost()]
        [Route("photo/export-photo-category")]
        public IActionResult ExportPhotoCategory()
        {

            BizData<QNExcelExportData> biz = si.ExportPhotoCategory(new PageRequest<PhotoCategoryBiz>());
            FileStreamResult fsr = File(biz.Data.ExportStream, biz.Data.OutFormat, biz.Data.FileName);
            return fsr;
        }
    }
}
